var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var lobby;
(function (lobby) {
    var view;
    (function (view) {
        var LobbyToolList = (function (_super) {
            __extends(LobbyToolList, _super);
            function LobbyToolList() {
                var _this = _super.call(this) || this;
                _this.btn_refresh = new ui.button.Button_Refresh();
                _this.addChild(_this.btn_refresh);
                var cut_off_line_0 = tool.BitmapTool.getInstance().createBitmapByName("cut_off_line_png");
                _this.addChild(cut_off_line_0);
                cut_off_line_0.x = 45;
                cut_off_line_0.y = 1;
                _this.btn_sd = new ui.button.Button_SD();
                _this.addChild(_this.btn_sd);
                _this.btn_sd.x = 65;
                _this.btn_sd.y = 0;
                _this.btn_hd = new ui.button.Button_HD();
                // this.addChild(this.btn_hd);
                _this.btn_hd.x = 65;
                _this.btn_hd.y = 0;
                var cut_off_line_1 = tool.BitmapTool.getInstance().createBitmapByName("cut_off_line_png");
                _this.addChild(cut_off_line_1);
                cut_off_line_1.x = 110;
                cut_off_line_1.y = 1;
                _this.btn_channel = new ui.button.Button_Channel();
                _this.addChild(_this.btn_channel);
                _this.btn_channel.x = 130;
                _this.btn_channel.y = 0;
                var cut_off_line_2 = tool.BitmapTool.getInstance().createBitmapByName("cut_off_line_png");
                _this.addChild(cut_off_line_2);
                cut_off_line_2.x = 175;
                cut_off_line_2.y = 1;
                _this.btn_detail = new ui.button.Button_Detail();
                _this.addChild(_this.btn_detail);
                _this.btn_detail.x = 196;
                _this.btn_detail.y = 1;
                var cut_off_line_3 = tool.BitmapTool.getInstance().createBitmapByName("cut_off_line_png");
                _this.addChild(cut_off_line_3);
                cut_off_line_3.x = 240;
                cut_off_line_3.y = 1;
                _this.btn_fullscreen = new ui.button.Button_FullScreen();
                _this.addChild(_this.btn_fullscreen);
                _this.btn_fullscreen.x = 261;
                _this.btn_fullscreen.y = 1;
                _this.btn_exit_fullscreen = new ui.button.Button_Exit_FullScreen();
                // this.addChild(this.btn_exit_fullscreen);
                _this.btn_exit_fullscreen.x = 261;
                _this.btn_exit_fullscreen.y = 1;
                var cut_off_line_4 = tool.BitmapTool.getInstance().createBitmapByName("cut_off_line_png");
                _this.addChild(cut_off_line_4);
                cut_off_line_4.x = 304;
                cut_off_line_4.y = 1;
                _this.btn_personal_info = new ui.button.Button_PersonInfo();
                _this.addChild(_this.btn_personal_info);
                _this.btn_personal_info.x = 326;
                _this.btn_personal_info.y = 0;
                var cut_off_line_5 = tool.BitmapTool.getInstance().createBitmapByName("cut_off_line_png");
                _this.addChild(cut_off_line_5);
                cut_off_line_5.x = 369;
                cut_off_line_5.y = 1;
                _this.btn_record = new ui.button.Button_Record();
                _this.addChild(_this.btn_record);
                _this.btn_record.x = 389;
                _this.btn_record.y = 0;
                var cut_off_line_6 = tool.BitmapTool.getInstance().createBitmapByName("cut_off_line_png");
                _this.addChild(cut_off_line_6);
                cut_off_line_6.x = 430;
                cut_off_line_6.y = 1;
                _this.btn_other = new ui.button.Button_Other();
                _this.addChild(_this.btn_other);
                _this.btn_other.x = 451;
                _this.btn_other.y = 0;
                var cut_off_line_7 = tool.BitmapTool.getInstance().createBitmapByName("cut_off_line_png");
                _this.addChild(cut_off_line_7);
                cut_off_line_7.x = 495;
                cut_off_line_7.y = 1;
                _this.btn_setting = new ui.button.Button_Setting();
                _this.addChild(_this.btn_setting);
                _this.btn_setting.x = 516;
                _this.btn_setting.y = 0;
                var cut_off_line_8 = tool.BitmapTool.getInstance().createBitmapByName("cut_off_line_png");
                _this.addChild(cut_off_line_8);
                cut_off_line_8.x = 554;
                cut_off_line_8.y = 1;
                _this.btn_exit = new ui.button.Button_Exit();
                _this.addChild(_this.btn_exit);
                _this.btn_exit.x = 573;
                _this.btn_exit.y = 0;
                return _this;
                // console.log("toollist初始化完成...");
                // console.log(this.width);
                // console.log(".........................");
            }
            return LobbyToolList;
        }(egret.DisplayObjectContainer));
        view.LobbyToolList = LobbyToolList;
        __reflect(LobbyToolList.prototype, "lobby.view.LobbyToolList");
    })(view = lobby.view || (lobby.view = {}));
})(lobby || (lobby = {}));
//# sourceMappingURL=LobbyToolList.js.map